from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution01
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution02
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution03
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution04
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution05
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution06
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution07
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution08
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution09
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution10
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution11
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution12
from PracticePythonExcercise.PracticePythonSolutions import PracticePythonSolution13

